### ISSUE TITLE
unable to get it working..

### ISSUE THREAD

**Issue by LySoon** [InfImpSolutions/IIS-EmergencyLS-ELS-FiveM#1]
i tried to change sirens active button in the case of if its disable by other resource but still same.
nothing happens.
K L etc works but no siren sound..
just beep sounds. i loved the idea how it works but does not work for me :(

**Comment by ThePlod1** [comment]
Are you using WM-ServerSirens. If you aren't, are you using the correct example XML file?

**Comment by rpworksmods** [comment]
If you refer to the FAQ in the ReadMe file, it does state that the 'gameName' value in your vehicles.meta and the xml file name must be identical for the resource to function correctly :)
