### ISSUE TITLE
Ambulance

### ISSUE THREAD

**Issue by Brightlight1988** [InfImpSolutions/IIS-EmergencyLS-ELS-FiveM#2]
Hi!
I got every car i replace to work with this good els but not the ambulance. L key and K key works and i have changed like you say in the pdf but still dont get it to work :/ and yes its a ELS car. 

Can you help me? adding every file you can look at it.
Q: Why won’t my primary lights turn on, but K and L
work?
A: The ‘gameName’ field in your vehicles.meta MUST
be identical to the model’s name! Not only is this good
practise in general, it is also the only way the code can
know if it’s an els vehicle or not at the moment.

[Desktop.zip](https://github.com/InfImpSolutions/IIS-EmergencyLS-ELS-FiveM/files/6094312/Desktop.zip)

//Bright

**Comment by Calumjn98** [comment]
is this the 2015 box aambo im having same problem

**Comment by Trko0045** [comment]
same issue

**Comment by rpworksmods** [comment]
This is no longer supported - Check out the new one at https://fivem.dragonhive.co.uk
