### ISSUE TITLE
Wigwag clash

### ISSUE THREAD

**Issue by Thewisemoustache** [InfImpSolutions/IIS-EmergencyLS-ELS-FiveM#3]
Great creation for my British server however an issue where controller is used, when the left D pad is pressed, the tail lights that enable traffic to yield come on but wont turn off when its pressed again to turn of the primary lights, any idea what is causing this? I've taken lux vehicle control out, just using ELS-FiveM, els-plus and IIS

**Comment by rpworksmods** [comment]
EmergencyLS is a standalone resource. ELS+ may clash with the functions of EmergencyLS, and it's unnecessary to have both installed simultaneously. Please remove ELS+
